### ISSUE TITLE
Ukol c.1. 

### ISSUE THREAD

**Issue by JitkaBorovickova** [JitkaBorovickova/python_2022#1]
https://github.com/JitkaBorovickova/python_2022/blob/main/ukol_1.py

Zkouska odevzdani ukolu c.1

Dekuji,
Jitka

**Comment by bromjiri** [comment]
Ahoj Jitko, 
tvoje řešení přesně splňuje zadání :)
Akorát teda ty řádky 15 a dále, to je předpokládám nějaká copy-paste chyba.

Každopádně dobrá práce, úkol splněn 👍 

Jirka
