### ISSUE TITLE
Ukol c.2

### ISSUE THREAD

**Issue by JitkaBorovickova** [JitkaBorovickova/python_2022#2]
Ahoj, posilam ke kontrole ukol c.2.
Moc dekuji za feedback.
Jitka
https://github.com/JitkaBorovickova/python_2022/blob/main/ukol_2.py

**Comment by bromjiri** [comment]
Ahoj Jitko,
tvoje řešení správně splňuje část zadání: _vypiš všechny státy, které leží v regionu_
Nicméně, neřeší tu druhou část: _Pokud program žádný stát pro daný region nenajde, vypiš text "Neznámý region"_

Pro tu druhou část je potřeba zjistit, jestli během celého cyklu byl alespoň jeden stát nalezen. 
To se dá do tvého kódu celkem snadno doplnit tím, že tam přidáš jednu proměnou, která změní hodnotu, pokud se podmínka aspoň jednou splní. Například takto:

```
region_found = False
for item in staty:
  name = item["name"]
  if region == item["region"]:
    print(f"{name}")
    region_found = True

if region_found == False:
    print("Neznámý region")
```

Jinak myslím, že to stačí, dobrá práce, úkol splněn 👍 :)
